### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by fabriciocolombo** [fabriciocolombo/delphi-rest-client-api#1]
Support to HTTPS connection

**Comment by RobertoSchneiders** [comment]
I'm using HTTPs with none problem at all.
@fabriciocolombo added support to configurable timeouts (https://github.com/fabriciocolombo/delphi-rest-client-api/commit/0345e23246c9b4f4dc0a4307f9f2f64ba1ce8bf6), so, I'll close this issue.
