### ISSUE TITLE
.GetAsDataSet() no Delphi XE3

### ISSUE THREAD

**Issue by fcmatos** [fabriciocolombo/delphi-rest-client-api#16]
Olá,

Gostei muito da API. Parabéns.
Gostaria de saber se tem alguma configuração a ser feita para utilizar no GetAsDataSet() no Delphi XE3.

Mensagem de erro:
[DCC Error] Unit1.pas(53): E2003 Undeclared identifier: 'GetAsDataSet'

**Comment by clederambrosini** [comment]
Ola. Estou começando com rest no delphi e estudando essa api, porem estou com esse problema [DCC Error] uFrm_PersonList.pas(61): E2003 Undeclared identifier: 'GetAsDataSet' o que posso fazer para resolver?
