### ISSUE TITLE
SuperObject vs DbxJson as default

### ISSUE THREAD

**Issue by vegar** [fabriciocolombo/delphi-rest-client-api#19]
You state that ["SuperObject is the default on supported platforms"](https://github.com/fabriciocolombo/delphi-rest-client-api/wiki/Serialization) but at the same time, `USE_SUPER_OBJECT` is undefined for `DELPHI_XE_UP`:

[DelphiRest.inc](https://github.com/fabriciocolombo/delphi-rest-client-api/blob/master/src/DelphiRest.inc#L76-L84)

``` delphi
{$DEFINE USE_SUPER_OBJECT}

{$IFDEF DELPHI_2010_UP}
  {$DEFINE USE_GENERICS}
{$ENDIF}

{$IFDEF DELPHI_XE_UP}
  {$UNDEF USE_SUPER_OBJECT}
{$ENDIF}
```

Who's right: The wiki or the code...?

**Comment by jhonatasobrinho** [comment]
How did you solve that? Can you explain with samples, please? Thanks!

**Comment by RobertoSchneiders** [comment]
@jhonatasobrinho If you are experiencing any problem, feel free to open a new issue and detail it
