### ISSUE TITLE
configure the timeout in TRestClient

### ISSUE THREAD

**Issue by RobertoSchneiders** [fabriciocolombo/delphi-rest-client-api#21]
This is a suggestion

It would be interesting if we could configure the timeouts (ResolveTimeout, ConnectTimeout, ConnectTimeout and ReceiveTimeout ) in the TRestClient. 

The defaults timeouts are different between Indy and WinHTTP. Sometimes the default values ​​do not meet the needs. Currently it is not possible change them. Or is it?

To change the timeouts via WinHTTP just use this method:
http://msdn.microsoft.com/en-us/library/windows/desktop/aa384061(v=vs.85).aspx

**Comment by Nashev** [comment]
For people like me, current proper link to TIdIOHandler.ReadTimeout property documentation online:

http://ww2.indyproject.org/docsite/html/frames.html?frmname=topic&frmfile=TIdTCPClientCustom_ReadTimeout.html
