### ISSUE TITLE
Are you alive?

### ISSUE THREAD

**Issue by RobertoSchneiders** [fabriciocolombo/delphi-rest-client-api#36]
I hope so. 

We have some important changes waiting in pull requests. Indeed, are 8 pull requests waiting for a long time. We are making a lot of improvements in this code but we simply can't contribute in this repository because it is abandoned. 

That way, we have our fork miles away from the original repo. We don't like it. Fragmenting this piece of code is not the best way of keep it moving, in my view.  

I hope you can add permissions to us (maybe some others contributors too) in this repo, that way, we can review, merge and continue to improve this framework. Otherwise, we have to mantain a fork of the same framework in two very different states. 

Best regards.

**Comment by esasse** [comment]
:+1:
