### ISSUE TITLE
On which Delphi version are you using rest client?

### ISSUE THREAD

**Issue by RobertoSchneiders** [fabriciocolombo/delphi-rest-client-api#40]
The framework documentation don't make clear what versions are supported and maintained. I think we should specify this. 

@fabriciocolombo was testing in a lot of versions, but, I don't think it will do it anymore.
```
The API was tested in Delphi 7, XE, XE2, XE3 and XE4. It is also compatible with Mac OSX and iOS.
```

I and the [monde-sistemas team](https://github.com/monde-sistemas/) are maintaining the code for Delphi XE7 (Win32), but, we can't test for all other (unused) versions. So, I need to know what versions we will support and who can help with tests.

I don't know any continuous integration service for Delphi, so, I think we have to do it manually.

**Comment by vonloxley** [comment]
My company will be using XE5 for another year, so I can run tests against that.

**Comment by RobertoSchneiders** [comment]
Great @vonloxley  :+1:

**Comment by thomaserlang** [comment]
XE3

**Comment by fabriciocolombo** [comment]
I am working with XE2, and i have currently installed D7, D2007, D2010, XE, XE3 and XE7.
I would like to support only 2010 or later, because of new features like new RTTI and Attributes.

**Comment by RobertoSchneiders** [comment]
So, let's support only 2010+ versions. Any objections?

**Comment by thomaserlang** [comment]
None.

**Comment by czar20** [comment]
I have been using on XE5 - now I am trying install on XE8 - no good.

unit DbxJsonUtils;

interface

uses SysUtils, DateUtils;

type
{$I DelphiRest.inc}

{$IFDEF USE_GENERICS}
  TJsonAttribute = class(TCustomAttribute)
  private
    FName: string;
  public
    constructor Create(const AName: string);
    property Name: string read FName;
  end;

  JsonName = class(TJsonAttribute);
  JsonDefault = class(TJsonAttribute);
  JsonISO8601 = class(TCustomAttribute);
{$ENDIF}  

implementation

Identifer expected but implementation found. Sorry I not clever enough to figure out what is wrong.

**Comment by RobertoSchneiders** [comment]
Probably the `USE_GENERICS` is not defined. 

Try to add this to the line 117 of the `DelphiRest.inc` file
```
{$IFDEF VER290} // RAD Studio XE8
  {$DEFINE DELPHI_7_UP}
  {$DEFINE DELPHI_2007_UP}
  {$DEFINE DELPHI_2009_UP}
  {$DEFINE DELPHI_2010_UP}
  {$DEFINE DELPHI_XE_UP}
  {$DEFINE DELPHI_XE2_UP}
  {$DEFINE DELPHI_XE3_UP}
  {$DEFINE DELPHI_XE4_UP}
  {$DEFINE DELPHI_XE5_UP}
  {$DEFINE DELPHI_XE6_UP}
  {$DEFINE DELPHI_XE7}
  {$DEFINE DELPHI_XE7_UP}
  {$DEFINE DELPHI_XE8}
  {$DEFINE DELPHI_XE8_UP}
{$ENDIF VER290}
```
It should work. If it works, send us a pull request, ok?

**Comment by czar20** [comment]
Yes that worked. I have never used GIT I am not sure how to do a pull request.

**Comment by RobertoSchneiders** [comment]
No problem @czar20, we will fix this.
