### ISSUE TITLE
Impliment support attributes for marshal/unmarshal

### ISSUE THREAD

**Issue by Frees** [fabriciocolombo/delphi-rest-client-api#41]
Since Delphi 2010 available attributes
http://docwiki.embarcadero.com/RADStudio/2010/en/Declaring_Custom_Attributes

We can use it for improve marshal/unmarshal 

For example:

```delphi
TSomeObject = class
   [TJsonField('fieldA')]
   filedAlpha: string;
end;
```
it'll be marshaled to (or unmarshal from)
```json
{"fieldA" : "someValue"}
```

**Comment by RobertoSchneiders** [comment]
Yeah, that seems great. :+1:

**Comment by Frees** [comment]
I`ll try implement my idea

**Comment by fabriciocolombo** [comment]
This is already supported. SuperObject implements the attributes SOName and SODefault. When using DBX there are the attributes JsonName and JsonDefault defined in DbxJsonUtils unit.

See the code inside TypesToTest.TAllTypes and the tests inside TestDbxJsonUnMarshal

    TAllTypes = class
      [SOName('renamed')]
      [JsonName('renamed')]
      fieldNameRenamed: String;

Maybe this could be improved.  Maybe remove the duplicated attribute.
Anyway, The docs should be improved to expose this feature.

Thanks.

**Comment by Frees** [comment]
Thanks Fabricio
