### ISSUE TITLE
Clean up compiler directives

### ISSUE THREAD

**Issue by fabriciocolombo** [fabriciocolombo/delphi-rest-client-api#43]
Clean up compiler directives using {$IF CompilerVersion >= XX} and more meaningful compiler directives names.
No more {$IFDEF VERXYZ}

**Comment by ronaldhoek** [comment]
Be sure to check the 'CONDITIONALEXPRESSIONS' define when using ```{$IF CompilerVersion >= XX.X}```

```Delphi
{$IFDEF CONDITIONALEXPRESSIONS}
  {$IF CompilerVersion >= 22.0}
    // etc.
  {$ENDIF}
{$ELSE}
  !!! UNSUPPORTED DELPHI VERSION !!!
{IFEND}
```

**Comment by fabriciocolombo** [comment]
Thanks for the tip
