### ISSUE TITLE
\ backslash in string property

### ISSUE THREAD

**Issue by JasonColeyNZ** [fabriciocolombo/delphi-rest-client-api#45]
I have a string property in an object that has backslashes (\) in the property and this seems to cause problems.

At the server the posted object appears as null.

If the backslashes are removed the posted object is removed.

Is there anything I should be doing to resolve this problem?

I am using Delphi XE6, VS2013 Community

**Comment by JasonColeyNZ** [comment]
OK, I switched to using SuperObject as it appears there is a long time delphi bug with backslashes not being parsed correctly, so uploading now works fine.

But now I have an issue with the updates coming down, I get a marshalling error and am not sure what to do now to get this working? any ideas?

**Comment by JasonColeyNZ** [comment]
the server is a WebApi and ASP.NET 5.0 rest site

**Comment by JasonColeyNZ** [comment]
Here is the json coming down to the delphi client.

'{"Project":null,"ProjectMember":null,"ProjectMemberStatus":null,"ProjectMemberName":null,"ProjectMemberPermissions":null,"ProjectMemberActive":null,"Subproject":null,"ListGroup":null,"List":null,"ThiredPartyLink":null,"Time":null,"TimeBunch":null,"TimeBunchPost":null,"Inbox":null,"Task":null,"TaskSubject":null,"TaskProjectID":null,"TaskSubProjectID":null,"TaskParentID":null,"TaskPriority":null,"TaskStatus":null,"TaskArchive":null,"TaskShowAllMembers":null,"TaskCreateDate":null,"TaskStartDate":null,"TaskDueDate":null,"TaskCompletedDate":null,"TaskBudget":null,"TaskBudgetType":null,"TaskBudgetLock":null,"TaskOwnerID":null,"TaskMember":null,"TaskMemberBudget":null,"TaskMemberStartDate":null,"TaskList":null,"Comment":null,"Attachment":[{"datamemo":"This note won''t get through.... or will it?\r\n\r\nc:\\testing\\paths\\with\\backslashes\\and\\more\\","datatype":1,"attachmentid":"{3FF9130A-834B-409D-AF97-BDEBD6CFA519}","md5":"","objectid":"{3A0C5B72-8A4E-48C2-8898-C45945462287}","objecttype":1,"projectmemberid":"","size":0,"modifieddate":2415017.95833333}],"Tag":null,"TaskTag":null,"UnitOfMeasure":null,"PackagingType":null,"Reminder":null,"Filter":null,"Sort":null,"Delete":null,"NavItem":null,"Id":0,"Description":"","SessionID":""}'

**Comment by fabriciocolombo** [comment]
The backslashes must be escaped.

     c:\\testing\\paths\\with\\backslashes\\and\\more\\"

**Comment by JasonColeyNZ** [comment]
Yeah I spotted that this morning, this what is being received from the server, so I will troubleshoot this next
