### ISSUE TITLE
JSON API support

### ISSUE THREAD

**Issue by esasse** [fabriciocolombo/delphi-rest-client-api#48]
I need a client that supports the [JSON API](http://jsonapi.org/) standard.

I was thinking about adding support for this format in this library instead of creating my own. 

I believe this could be done just like the abstraction of the HTTP connection. By default it would use the current plain JSON format, but a another "adapter" could be set to change the format.

Do you think it's a good idea?

**Comment by RobertoSchneiders** [comment]
Yeah, absolutely.

**Comment by esasse** [comment]
Thanks, I'll send a PR if we follow this idea.
