### ISSUE TITLE
Passing Array Type

### ISSUE THREAD

**Issue by Timothyoverton** [fabriciocolombo/delphi-rest-client-api#54]
Hi Guys,

I have this working with a single object but when I add in array of objects, I get nothing back.

This was working:
type 
  TLoginResponse = class
    public
      id: string;
  end;
var
 loginResponse: TLoginResponse;
begin
loginResponse := FabRestClient.Resource('https://blah//ro')
                   .Accept(RestUtils.MediaType_Json)
                   .contentType(RestUtils.MediaType_Json)
                   .Post<TLoginResponse>(body);

This isn't, although the call is returning 200 and there is a result in Fiddler:
type
        TAccountArray = TArray<TAccount>;
      var
        test: TAccountArray;
begin
        test := DelphiRestClient.Resource(baseApi + url)
                 .Header('Authorization', 'Bearer ' + bearerToken)
                 .Accept(RestUtils.MediaType_Json)
                 .Get<TAccountArray>();

In the IDE hovering over Get its only giving me the string parameter, so I've added in the USE_GENERICS directive to the compiler. It won't allow me to add TArray<TAccount> as the Get parameter, it says type mismatch. Any thoughts?

**Comment by thomaserlang** [comment]
You need to specify what it has to return it as.

Try: Get<TheTYPE>()

Check the examples in the readme file.

**Comment by Timothyoverton** [comment]
Thanks Thomas,

I was able to get it working with TList<TAccount>. However, TArray<TAccount> would not pass the returned data. Also I ended up using TObjectList<TAccount> however, when this is passed back by the RestClient, OwnsObjects of TObjectList is set to false. I've been able to get around this by creating my own descendant which forces OwnObjects to true, so that you can call Free and the TAccounts are free'd as well.
-----------------------
 TBfObjectList<T: class> = class(TObjectList<T>)
    published
      constructor Create;
  end;

constructor TBfObjectList<T>.Create;
begin
  Inherited Create;
  FOwnsObjects := true;
end;
-----------------------

Is TArray<> not supported? (I'm using XE6.)

**Comment by Timothyoverton** [comment]
I will use TList or my own TObjectList - thanks.
