### ISSUE TITLE
ContentTypes

### ISSUE THREAD

**Issue by rafakwolf** [fabriciocolombo/delphi-rest-client-api#57]
How can i set ContentType = 'application/x-www-form-urlencoded' ?

Thanks

**Comment by RobertoSchneiders** [comment]
This should work (from Post example):
```
RestClient.Resource('http://localhost:8080/java-rest-server/rest/person')
            .Accept(RestUtils.MediaType_Json)
            .ContentType('application/x-www-form-urlencoded')
            .Post<TPerson>(vPerson);
```

**Comment by rafakwolf** [comment]
Thanks!

**Comment by rafakwolf** [comment]
@RobertoSchneiders 

Did not work :(

**Comment by RobertoSchneiders** [comment]
What exactly is happening @rafakwolf?

**Comment by rafakwolf** [comment]
The APIs with Bearer Token authentication, needs the **application/x-www-form-urlencoded** to request for tokens... so, the receiving response is ( _unsupported grant_type_ ) with status code 400.

**Comment by RobertoSchneiders** [comment]
@rafakwolf I don't think this is a problem related to this library. 

The error `unsupported grant_type` suggest that you are not passing the correct `grant_type` parameter to the request or you are not informing this parameter at all. 

It should  look like this:
```
grant_type=password&username=yourusername&password=yourpassword
```
http://stackoverflow.com/a/29261024

If this doesn't help, can you share your code with us? What API you are trying to consume?

**Comment by fabriciocolombo** [comment]
Closed by inactivity.
