### ISSUE TITLE
Large upload/download progress

### ISSUE THREAD

**Issue by Timothyoverton** [fabriciocolombo/delphi-rest-client-api#60]
Hi Guys,

1 of the nice features of the Indy components is their ability through events to let us know of the progress of a large post/get, upload/download. 

Do you have compatible WorkBegin/Work/WorkEnd events in which we can monitor the progress of a rest call? Or an example of a rest call with callback/synchronize events?

Thanks Tim

**Comment by Timothyoverton** [comment]
I'm guessing that's a no?

**Comment by RobertoSchneiders** [comment]
Yeah, probably. I haven't done anything like that yet, sorry.

**Comment by fabriciocolombo** [comment]
I also haven't done anything like that yet.
Can you send a PR @Timothyoverton?

**Comment by Timothyoverton** [comment]
Yes I will - as soon as I have a moment. Someone else did something very similar in the last 2 months...can't find the PR right now. I'll close this for now.
