### ISSUE TITLE
DbxJsonUtils.pas fails to build in pre-Generic Delphi versions

### ISSUE THREAD

**Issue by darianmiller** [fabriciocolombo/delphi-rest-client-api#62]
'Type' is outside the {$IFDEF USE_GENERICS} block, so if generics aren't available, compiler error in Delphi 2007:  "Identifier expected but 'IMPLEMENTATION' found"

**Comment by RobertoSchneiders** [comment]
@darianmiller thanks for report that, can you send us a pull request?

**Comment by darianmiller** [comment]
Ok, pull request created...failed to include issue number in comment.

**Comment by RobertoSchneiders** [comment]
No problem, thanks for contributing.
