### ISSUE TITLE
Hello, I have try to test you REST api, but have a error when complile it. 

### ISSUE THREAD

**Issue by wqmeng** [fabriciocolombo/delphi-rest-client-api#7]
class function TJsonUtilGenerics.Marshal(entity: TObject): string;
begin
  Result := entity.ToJson().AsJSon();
end;

[DCC Error] RestJsonGenerics.pas(26): E2003 Undeclared identifier: 'ToJson'

Is the function ToJson still not implement yet?  Or I have miss something?

Thanks

**Comment by leacarbonera** [comment]
Olá, Fabricio tudo bem. Estou tentando instalar a biblioteca RestClient no meu Delphi XE2, mas ao compilar me apresenta o seguinte erro no arquivo Restclient.pas, na função :

function TResource.Post(Entity: TObject): TObject;
begin
  Result := Post(Entity, Entity.ClassType);
end;

"[DCC Error] RestClient.pas(1001): E2250 There is no overloaded version of 'Post' that can be called with these arguments"

O que pode ser será?

Abraço

**Comment by berniQ23** [comment]
I can confirm the comment from Abraco from November 2017.
A fresh checkout from today gives on compiling DelphiXE4_RestApi.bpl:

[dcc32 Fehler] RestClient.pas(1001): E2250 Es gibt keine überladene Version von 'Post', die man mit diesen Argumenten aufrufen kann
=> 
function TResource.Post(Entity: TObject): TObject;
begin
  Result := Post(Entity, Entity.ClassType);
end;

[dcc32 Fehler] RestClient.pas(1028): E2250 Es gibt keine überladene Version von 'Put', die man mit diesen Argumenten aufrufen kann
=>
function TResource.Put(Entity: TObject): TObject;
begin
  Result := Put(Entity, Entity.ClassType);
end;

[dcc32 Fehler] RestClient.pas(1065): E2250 Es gibt keine überladene Version von 'Patch', die man mit diesen Argumenten aufrufen kann
=>
function TResource.Patch(Entity: TObject): TObject;
begin
  Result := Patch(Entity, Entity.ClassType);
end;

How to fix it?
Regards,
Bernd
